// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevelopmentFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeJBQrUr0dmvpOdxwF3EtB5yeztSiUavU',
    appId: '1:675682001870:web:9bf93789240072a7bd819f',
    messagingSenderId: '675682001870',
    projectId: 'grro-copy',
    authDomain: 'grro-copy.firebaseapp.com',
    storageBucket: 'grro-copy.firebasestorage.app',
    measurementId: 'G-J3LCC7ZQP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEMXuh8Mo9-_lYFJlU-D6qSLwD9v_PsDU',
    appId: '1:675682001870:android:c8062e44330dee49bd819f',
    messagingSenderId: '675682001870',
    projectId: 'grro-copy',
    storageBucket: 'grro-copy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD10nr6BVMcO2F5nVhFcvmth79y5lhaa8s',
    appId: '1:675682001870:ios:ed8f460dc1778d1ebd819f',
    messagingSenderId: '675682001870',
    projectId: 'grro-copy',
    storageBucket: 'grro-copy.firebasestorage.app',
    iosBundleId: 'com.syfton.grroBusinessApp',
  );
}
