// File generated by FlutterFire CLI.
// ignoreforfile: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_pro.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProductionFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm46HN25WiQC5f1W03wAkJzLi_3us76Iw',
    appId: '1:574909873629:android:39261fb0eee742ca3bca34',
    messagingSenderId: '574909873629',
    projectId: 'i-canyon-marketing-app',
    storageBucket: 'i-canyon-marketing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRtaD2D4tLk-JvZpDIS0B7gA5_jawh_9s',
    appId: '1:574909873629:ios:48b35fb781b42b193bca34',
    messagingSenderId: '574909873629',
    projectId: 'i-canyon-marketing-app',
    storageBucket: 'i-canyon-marketing-app.firebasestorage.app',
    iosClientId: '574909873629-rcs33lauj2d3ei6dbiuj740mjmoqs9jk.apps.googleusercontent.com',
    iosBundleId: 'com.syfton.grroBusinessApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADaZLCOLHraKDbWjwKIqsJRmaoEJWsotQ',
    appId: '1:574909873629:web:1c0ca45ce48f9c273bca34',
    messagingSenderId: '574909873629',
    projectId: 'i-canyon-marketing-app',
    authDomain: 'i-canyon-marketing-app.firebaseapp.com',
    storageBucket: 'i-canyon-marketing-app.firebasestorage.app',
    measurementId: 'G-9F8KR06BBX',
  );

}
