final List<String> allCities = [
  'Alappuzha',
  'Ernakulam',
  'Idukki',
  'Kannur',
  'Kasaragod',
  'Kollam',
  'Kottayam',
  'Kozhikode',
  'Malappuram',
  'Palakkad',
  'Pathanamthitta',
  'Thiruvananthapuram',
  'Thrissur',
  'Wayanad',
  'Riyadh',
  'Makkah',
  'Madinah',
  'Eastern Province',
  'Asir',
  'Jazan',
  'Najran',
  'Al Bahah',
  'Al Jawf',
  'Tabuk',
  'Hail',
  'Qassim',
  'Abu Dhabi',
  'Dubai',
  'Sharjah',
  'Ajman',
  'Umm Al Quwain',
  'Ras Al Khaimah',
  'Fujairah',
  'Doha',
  'Al Rayyan',
  'Al Wakrah',
  'Al Khor',
  'Al Daayen',
  'Umm Salal',
  'Al Shahaniya',
  'Al Asimah',
  'Hawalli',
  'Farwaniya',
  'Mubarak Al-Kabeer',
  'Ahmadi',
  'Jahra',
  'Muscat',
  'Dhofar',
  'Al Batinah North',
  'Al Batinah South',
  'Ad Dakhiliyah',
  'Ash Sharqiyah North',
  'Ash Sharqiyah South',
  'Al Dhahirah',
  'Al Buraimi',
  'Musandam',
  'Al Wusta',
  'Capital Governorate',
  'Muharraq Governorate',
  'Northern Governorate',
  'Southern Governorate',
  'Bengaluru',
  'Hyderabad',
  'Chennai',
  'Pune',
  'Mumbai',
  'Navi Mumbai',
  'Thane',
  'Noida',
  'Gurugram',
  'Faridabad',
  'Ahmedabad',
  'Gandhinagar',
  'Kolkata',
  'Vijayawada',
  'Visakhapatnam',
  'Coimbatore',
  'Madurai',
  'Indore',
  'Jaipur',
  'Mohali',
];

final List<Map<String, dynamic>> places = [
  // Kerala Districts (India)
  {"name": "Alappuzha", "country": "India", "image": "assets/city/alappuzha.svg"},
  {"name": "Ernakulam", "country": "India", "image": "assets/city/ernakulam.svg"},
  {"name": "Idukki", "country": "India", "image": "assets/city/idukki.svg"},
  {"name": "Kannur", "country": "India", "image": "assets/city/kannur.svg"},
  {"name": "Kasaragod", "country": "India", "image": "assets/city/kasarkode.svg"},
  {"name": "Kollam", "country": "India", "image": "assets/city/kollam.svg"},
  {"name": "Kottayam", "country": "India", "image": "assets/city/kottayam.svg"},
  {"name": "Kozhikode", "country": "India", "image": "assets/city/kozikode.svg"},
  {"name": "Malappuram", "country": "India", "image": "assets/city/malappuram.svg"},
  {"name": "Palakkad", "country": "India", "image": "assets/city/palakkad.svg"},
  {"name": "Pathanamthitta", "country": "India", "image": "assets/city/pathanamthitta.svg"},
  {"name": "Thiruvananthapuram", "country": "India", "image": "assets/city/tvm.svg"},
  {"name": "Thrissur", "country": "India", "image": "assets/city/thrissur.svg"},
  {"name": "Wayanad", "country": "India", "image": "assets/city/wayanad.svg"},

  // Saudi Arabia
  {"name": "Riyadh", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Riyadh_skyline.jpg"},
  {"name": "Makkah", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Great_Mosque_of_Mecca.jpg"},
  {"name": "Madinah", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Al-Masjid_an-Nabawi.jpg"},
  {"name": "Eastern Province", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/3/32/Dammam_Corniche.jpg"},
  {"name": "Asir", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Asir_Mountains.jpg"},
  {"name": "Jazan", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Jazan_Coast.jpg"},
  {"name": "Najran", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/1/14/Najran_Fort.jpg"},
  {"name": "Al Bahah", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Al_Baha_Mountains.jpg"},
  {"name": "Al Jawf", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Dumat_Al_Jandal.jpg"},
  {"name": "Tabuk", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/6/67/Tabuk_Castle.jpg"},
  {"name": "Hail", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/5/56/Hail_Desert.jpg"},
  {"name": "Qassim", "country": "Saudi Arabia", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Buraydah_City.jpg"},

  // UAE
  {"name": "Abu Dhabi", "country": "UAE", "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Sheikh_Zayed_Grand_Mosque.jpg"},
  {"name": "Dubai", "country": "UAE", "image": "https://upload.wikimedia.org/wikipedia/commons/9/93/Burj_Khalifa.jpg"},
  {"name": "Sharjah", "country": "UAE", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Sharjah_Corniche.jpg"},
  {"name": "Ajman", "country": "UAE", "image": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Ajman_Beach.jpg"},
  {"name": "Umm Al Quwain", "country": "UAE", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Umm_Al_Quwain_Fort.jpg"},
  {"name": "Ras Al Khaimah", "country": "UAE", "image": "https://upload.wikimedia.org/wikipedia/commons/4/47/Jebel_Jais.jpg"},
  {"name": "Fujairah", "country": "UAE", "image": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Fujairah_Mosque.jpg"},

  // Qatar
  {"name": "Doha", "country": "Qatar", "image": "https://upload.wikimedia.org/wikipedia/commons/7/75/Doha_Skyline.jpg"},
  {"name": "Al Rayyan", "country": "Qatar", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2d/Education_City_Qatar.jpg"},
  {"name": "Al Wakrah", "country": "Qatar", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Al_Wakrah_Souq.jpg"},
  {"name": "Al Khor", "country": "Qatar", "image": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Al_Khor_Corniche.jpg"},
  {"name": "Al Daayen", "country": "Qatar", "image": "https://upload.wikimedia.org/wikipedia/commons/5/56/Lusail_City.jpg"},
  {"name": "Umm Salal", "country": "Qatar", "image": "https://upload.wikimedia.org/wikipedia/commons/6/69/Umm_Salal_Mohammed_Fort.jpg"},
  {"name": "Al Shahaniya", "country": "Qatar", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Sheikh_Faisal_Museum.jpg"},

  // Kuwait
  {"name": "Al Asimah", "country": "Kuwait", "image": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Kuwait_Towers.jpg"},
  {"name": "Hawalli", "country": "Kuwait", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Hawalli_City.jpg"},
  {"name": "Farwaniya", "country": "Kuwait", "image": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Farwaniya_City.jpg"},
  {"name": "Mubarak Al-Kabeer", "country": "Kuwait", "image": "https://upload.wikimedia.org/wikipedia/commons/6/63/Mubarak_Al_Kabeer.jpg"},
  {"name": "Ahmadi", "country": "Kuwait", "image": "https://upload.wikimedia.org/wikipedia/commons/5/56/Ahmadi_City.jpg"},
  {"name": "Jahra", "country": "Kuwait", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Jahra_City.jpg"},

  // Oman
  {"name": "Muscat", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3f/Muscat_Corniche.jpg"},
  {"name": "Dhofar", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Salalah_Monsoon.jpg"},
  {"name": "Al Batinah North", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Sohar_Fort.jpg"},
  {"name": "Al Batinah South", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Rustaq_Fort.jpg"},
  {"name": "Ad Dakhiliyah", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/5/5e/Nizwa_Fort.jpg"},
  {"name": "Ash Sharqiyah North", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Wahiba_Sands.jpg"},
  {"name": "Ash Sharqiyah South", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Sur_Oman.jpg"},
  {"name": "Al Dhahirah", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Ibri_Fort.jpg"},
  {"name": "Al Buraimi", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Al_Buraimi.jpg"},
  {"name": "Musandam", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/6/6e/Khasab_Fjord.jpg"},
  {"name": "Al Wusta", "country": "Oman", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Duqm_Port.jpg"},

  // Bahrain
  {"name": "Capital Governorate", "country": "Bahrain", "image": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Manama_Skyline.jpg"},
  {"name": "Muharraq Governorate", "country": "Bahrain", "image": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Muharraq_Houses.jpg"},
  {"name": "Northern Governorate", "country": "Bahrain", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3f/Barbar_Temple.jpg"},
  {"name": "Southern Governorate", "country": "Bahrain", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Tree_of_Life_Bahrain.jpg"},

  // India Tech Cities
  {"name": "Bengaluru", "country": "India", "image": "assets/city/banglore.svg"},
  {"name": "Delhi", "country": "India", "image": "assets/city/delhi.svg"},
  {"name": "Hyderabad", "country": "India", "image": "assets/city/hyderbad.svg"},
  {"name": "Chennai", "country": "India", "image": "assets/city/chennai.svg"},
  {"name": "Pune", "country": "India", "image": "assets/city/pune.svg"},
  {"name": "Mumbai", "country": "India", "image": "assets/city/mumbai.svg"},
  {"name": "Kolkata", "country": "India", "image": "assets/city/kolkata.svg"},
  {"name": "Noida", "country": "India", "image": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Noida_City.jpg"},
  {"name": "Gurugram", "country": "India", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Gurgaon_Skyline.jpg"},
  {"name": "Ahmedabad", "country": "India", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Sabarmati_Riverfront.jpg"},
  {"name": "Vijayawada", "country": "India", "image": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Krishna_River_Vijayawada.jpg"},
  {"name": "Visakhapatnam", "country": "India", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9b/RK_Beach_Vizag.jpg"},
  {"name": "Coimbatore", "country": "India", "image": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Coimbatore_City.jpg"},
  {"name": "Madurai", "country": "India", "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Meenakshi_Temple.jpg"},
  {"name": "Indore", "country": "India", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Rajwada_Indore.jpg"},
  {"name": "Jaipur", "country": "India", "image": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Hawa_Mahal.jpg"},
  {"name": "Mohali", "country": "India", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Mohali_City.jpg"},
];
